[package]
name = "simple-calc"
version = "0.1.9"
edition = "2024"
authors = ["Frinz Sundiang <sundiangfrinz84@gmail.com>"]
description = "A (not so) simple CLI calculator made in Rust."
license = "MIT"
repository = "https://github.com/serendipityfrinz/simple-calc"
readme = "README.md"
keywords = ["calculator", "cli", "terminal", "math", "interactive"]
categories = ["command-line-utilities", "parsing"]

[dependencies]
clearscreen = "4.0.6"
colored = "3.1.1"
inquire = "0.9.4"
