[package]
name = "simple-calc"
description = "A simple, very overengineered calculator made in Rust."
authors = ["Frinz Sundiang sundiangfrinz84@gmail.com"]
license = "MIT"
repository = "https://github.com/serendipityfrinz/simple-calc/"
version = "0.1.1"
edition = "2024"
readme = "README.md"

[dependencies]
colored = "3.1.1"
inquire = "0.9.4"
